title: Antiderivative
email: abiola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Some personal musings on computing, mathematics and programming.
github_username:  alapite

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
